-- Sales Partner full profile: personal, address, KYC and bank verification.
ALTER TABLE `agent_profiles`
  ADD COLUMN `alt_phone` VARCHAR(20) NULL,
  ADD COLUMN `dob` DATE NULL,
  ADD COLUMN `gender` VARCHAR(20) NULL,
  ADD COLUMN `addr_line1` VARCHAR(200) NULL,
  ADD COLUMN `addr_line2` VARCHAR(200) NULL,
  ADD COLUMN `addr_area` VARCHAR(150) NULL,
  ADD COLUMN `addr_city` VARCHAR(100) NULL,
  ADD COLUMN `addr_district` VARCHAR(100) NULL,
  ADD COLUMN `addr_state` VARCHAR(100) NULL,
  ADD COLUMN `addr_pincode` VARCHAR(10) NULL,
  ADD COLUMN `addr_country` VARCHAR(100) NULL,
  ADD COLUMN `aadhaar_enc` VARCHAR(500) NULL,
  ADD COLUMN `aadhaar_last4` VARCHAR(4) NULL,
  ADD COLUMN `aadhaar_doc` VARCHAR(255) NULL,
  ADD COLUMN `pan_enc` VARCHAR(500) NULL,
  ADD COLUMN `pan_last4` VARCHAR(4) NULL,
  ADD COLUMN `pan_doc` VARCHAR(255) NULL,
  ADD COLUMN `kyc_status` ENUM('not_submitted', 'pending', 'verified', 'rejected') NOT NULL DEFAULT 'not_submitted',
  ADD COLUMN `kyc_remarks` VARCHAR(255) NULL,
  ADD COLUMN `kyc_reviewed_at` TIMESTAMP(0) NULL,
  ADD COLUMN `kyc_reviewed_by` BIGINT UNSIGNED NULL,
  ADD COLUMN `bank_branch` VARCHAR(150) NULL,
  ADD COLUMN `bank_proof_doc` VARCHAR(255) NULL,
  ADD COLUMN `bank_status` ENUM('not_submitted', 'pending', 'verified', 'rejected') NOT NULL DEFAULT 'not_submitted',
  ADD COLUMN `bank_remarks` VARCHAR(255) NULL,
  ADD COLUMN `bank_reviewed_at` TIMESTAMP(0) NULL,
  ADD COLUMN `bank_reviewed_by` BIGINT UNSIGNED NULL;
